### PR TITLE
Fix critical npm audit issues

### PR DESCRIPTION
**Pull request by petemill**
Force resolve of immer and set-value to solve security advisories.
- npx npm-force-resolutions was used to apply package.json resolutions field to package-lock.json. npm ci should be used to replicate package-lock.json. npm install will just overwrite with insecure versions of transient dependencies

Convert yarn.lock to package-lock.json
- This is to ensure we can pin transient dependencies via npm's `npm ci` command (instead of `npm install`). Brave Browser doesn't use `yarn`.

### CODE REVIEW

**Comment by remusao** [comment]
Can we maybe create the lock with a newer version of npm?
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
```

I still see the issue with repos coming form GitHub:
```
npm WARN old lockfile HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/star-wasm - Not found
npm WARN old lockfile     at /home/remi/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm WARN old lockfile     at async Array.<anonymous> (/home/remi/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9)
npm WARN old lockfile  Could not fetch metadata for star-wasm@0.1.3 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/star-wasm - Not found
npm WARN old lockfile     at /home/remi/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm WARN old lockfile     at async Array.<anonymous> (/home/remi/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     date: [ 'Thu, 11 Nov 2021 07:33:35 GMT' ],
npm WARN old lockfile     'content-type': [ 'application/json' ],
npm WARN old lockfile     'content-length': [ '21' ],
npm WARN old lockfile     connection: [ 'keep-alive' ],
npm WARN old lockfile     'cf-ray': [ '6ac5d54acb496921-FRA' ],
npm WARN old lockfile     vary: [ 'Accept-Encoding' ],
npm WARN old lockfile     'expect-ct': [
npm WARN old lockfile       'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
npm WARN old lockfile     ],
npm WARN old lockfile     server: [ 'cloudflare' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 404,
npm WARN old lockfile   code: 'E404',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://registry.npmjs.org/star-wasm',
npm WARN old lockfile   body: { error: 'Not found' },
npm WARN old lockfile   pkgid: 'star-wasm@0.1.3'
npm WARN old lockfile }
```

The `npm ci` still succeeds in the end but it would be nice to not have these warnings.

**Comment by remusao** [comment]
I have pushed a fix for CI.

**Comment by petemill** [comment]
@remusao brave browser is still on npm 6, so I am using that for this too. We are due to upgrade soon. I noticed that build.yml / CI is fixed to node 14 which should also be npm 6. But the Dockerfile for integration tests is just latest npm

**Comment by petemill** [comment]
We can pin Dockerfile to `node:14-buster` or leave as-is since it works and we will upgrade node soon

**Comment by petemill** [comment]
Closing in favor of https://github.com/brave/web-discovery-project/pull/71 because it initially seemed like not all CI ran for this?

**Pull request closed without merging**
